=== dsterle/eurovision/XML und Schemata/ESC.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.1"> 

<xs:element name ="ESC">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="Contest" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name ="Logo" type ="xs:anyURI" minOccurs="1" maxOccurs="1"/>
                        <xs:element name ="Bühnenbild" type ="xs:anyURI" minOccurs="1" maxOccurs="1"/>
                        <xs:element name ="Titelbild" type ="xs:anyURI" minOccurs="1" maxOccurs="1"/>
                        <xs:element name ="Informationstext" type ="xs:string" minOccurs="1" maxOccurs="1"/>
                        <xs:element name ="Teilnehmer" minOccurs="20" maxOccurs="46">                            
                        <xs:complexType>
                            <xs:sequence>
                            <xs:element name ="Land" type="xs:string" minOccurs="1" maxOccurs="1"/>
                            <xs:element name ="Vertreter" minOccurs="1" maxOccurs="1">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:string">                                       
                                        <xs:attribute name ="Geschlecht">
                                            <xs:simpleType>
                                                <xs:restriction base ="xs:string">
                                                    <xs:enumeration value ="Männlich"/>
                                                    <xs:enumeration value ="Weiblich"/>
                                                    <xs:enumeration value ="Gemischt"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:attribute>
                                    </xs:extension>
                                </xs:simpleContent>                   
                            </xs:complexType>
                        </xs:element>
                        <xs:element name ="Song" minOccurs="1" maxOccurs="1">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base ="xs:string">
                                        <xs:attribute name ="Sprache" type ="xs:language"/>                             
                                    </xs:extension>
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name ="grobePlatzierung" minOccurs="1" maxOccurs="1">
                            <xs:simpleType>
                                <xs:restriction base ="xs:string">
                                    <xs:enumeration value ="Finale"/>
                                    <xs:enumeration value ="Halbfinale"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name ="genauePlatzierung" minOccurs="1" maxOccurs="1">
                            <xs:simpleType>
                                <xs:restriction base ="xs:integer">
                                    <xs:pattern value="[0-2][0-9]"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        </xs:sequence>
                        </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name ="Jahr">
                        <xs:simpleType>
                            <xs:restriction base ="xs:integer">
                                <xs:pattern value="[2][0-9][1-9][0-9]"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== dsterle/eurovision/XML und Schemata/ESC.xml
<?xml version="1.0" encoding="UTF-8"?>
<ESC xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ESC.xsd">

<Contest Jahr ="2010">
    
    <Logo> ..\Bilder\Logos\2010.jpg </Logo>
    <Bühnenbild> ..\Bilder\Bühnenbilder\2010.jpg </Bühnenbild>
    <Titelbild> ../Bilder/Titelbilder/2010.jpg </Titelbild>
    <Informationstext> Der 55. Eurovision Song Contest fand am 25., 27. und 29. Mai 2010 in der Telenor Arena im Ballungsraum von Oslo, 
        Norwegen statt. Das Land war damit zum dritten Mal Veranstaltungsort, nachdem der norwegische Beitrag Fairytale 
        von Alexander Rybak im Vorjahr den 54. Eurovision Song Contest in Moskau gewonnen hatte. 39 Länder nahmen teil.
        Alle drei Sendungen wurden von Erik Solbakken, Haddy N’jie und Nadia Hasnaoui moderiert. Der deutsche Beitrag Satellite, 
        ein Lied der US-amerikanischen Songwriterin Julie Frost und des dänischen Komponisten John Gordon, wurde von der Sängerin 
        Lena Meyer-Landrut vorgetragen und errang den Sieg beim Wettbewerb.
        Die Veranstaltung stand unter dem Motto „Share the Moment“. Vor den Auftritten der Künstler wurden kurze Videoclips gezeigt, 
        die im jeweiligen Teilnehmerland entstanden waren. Im Finale wurden zusätzlich am Anfang der Sendung und nach jedem Lied Bilder 
        aus Wohnzimmern des jeweiligen Landes eingeblendet. Zwischen der Präsentation der Lieder und der Bekanntgabe der Ergebnisse wurden 
        Bilder vom sogenannten Eurovision Flash Mob Dance aus verschiedenen europäischen Städten gezeigt. 
    </Informationstext>
    
    <Teilnehmer> 
        <Land> Albanien </Land>
        <Vertreter Geschlecht ="Weiblich"> Juliana Pasha </Vertreter>
        <Song Sprache ="en"> It's All About You </Song>
        <grobePlatzierung>Finale</grobePlatzierung>
        <genauePlatzierung> 16 </genauePlatzierung>
    </Teilnehmer>
    
    
    <Teilnehmer> 
        <Land> Armenien </Land> 
        <Vertreter Geschlecht ="Weiblich"> Eva Rivas </Vertreter>
        <Song Sprache ="en"> Apricot Stone </Song>
        <grobePlatzierung>Finale</grobePlatzierung>
        <genauePlatzierung> 07 </genauePlatzierung> 
    </Teilnehmer>
    
    <Teilnehmer> 
        <Land> Aserbaidschan </Land>
        <Vertreter Geschlecht ="Weiblich"> Safura </Vertreter>
        <Song Sprache ="en"> Drip Drop </Song>
        <grobePlatzierung>Finale</grobePlatzierung>
        <genauePlatzierung> 05 </genauePlatzierung>
    </Teilnehmer>
    
    <Teilnehmer> 
        <Land> Belgien </Land>
        <Vertreter Geschlecht ="Männlich"> Tom Dice </Vertreter>
        <Song Sprache ="en"> Me And My Guitar </Song>
        <grobePlatzierung>Finale</grobePlatzierung>
        <genauePlatzierung> 06 </genauePlatzierung>
    </Teilnehmer>
    
    <Teilnehmer> 
        <Land> Bosnien-Herzegowina </Land>
        <Vertreter Geschlecht ="Männlich"> 	Vukasin Brajic </Vertreter>
        <Song Sprache ="en"> Lightning And Thunder </Song>
        <grobePlatzierung>Finale</grobePlatzierung>
        <genauePlatzierung> 17 </genauePlatzierung>
    </Teilnehmer>
    
    <Teilnehmer> 
        <Land> Bulgarien </Land>
        <Vertreter Geschlecht ="Weiblich"> Miro </Vertreter>
        <Song Sprache ="bg"> Angel si ti </Song>
        <grobePlatzierung>Halbfinale</grobePlatzierung>
        <genauePlatzierung> 15 </genauePlatzierung>
    </Teilnehmer>
    
    <Teilnehmer> 
        <Land> Dänemark </Land>
        <Vertreter Geschlecht ="Gemischt"> 	Chanée/N’Evergreen </Vertreter>
        <Song Sprache ="en"> In a Moment like This </Song>
        <grobePlatzierung>Finale</grobePlatzierung>
        <genauePlatzierung> 04 </genauePlatzierung>
    </Teilnehmer>
    
    <Teilnehmer> 
        <Land> Deutschland </Land>
        <Vertreter Geschlecht ="Weiblich"> Lena </Vertreter>
        <Song Sprache ="en"> Satellite </Song>
        <grobePlatzierung>Finale</grobePlatzierung>
        <genauePlatzierung> 01 </genauePlatzierung>
    </Teilnehmer>
    
    <Teilnehmer> 
        <Land> Estland </Land>
        <Vertreter Geschlecht ="Männlich"> Malcolm Lincoln/Manpower </Vertreter>
        <Song Sprache ="en"> Siren </Song>
        <grobePlatzierung>Halbfinale</grobePlatzierung>
        <genauePlatzierung> 14 </genauePlatzierung>
    </Teilnehmer>
    
    <Teilnehmer> 
        <Land> Finnland </Land>
        <Vertreter Geschlecht ="Weiblich"> Kuunkuiskaajat </Vertreter>
        <Song Sprache ="fin"> Työlki ellää </Song>
        <grobePlatzierung>Halbfinale</grobePlatzierung>
        <genauePlatzierung> 11 </genauePlatzierung>
    </Teilnehmer>
    
    <Teilnehmer> 
        <Land> Frankreich </Land>
        <Vertreter Geschlecht ="Männlich"> Jessy Matador </Vertreter>
        <Song Sprache ="fr"> Allez olla olé </Song>
        <grobePlatzierung>Finale</grobePlatzierung>
        <genauePlatzierung> 12 </genauePlatzierung>
    </Teilnehmer>
    
    <Teilnehmer> 
        <Land> Georgien </Land>
        <Vertreter Geschlecht ="Weiblich"> Sofia Nizharadze </Vertreter>
        <Song Sprache ="en"> Shine </Song>
        <grobePlatzierung>Finale</grobePlatzierung>
        <genauePlatzierung> 09 </genauePlatzierung>
    </Teilnehmer>
    
    <Teilnehmer> 
        <Land> Griechenland </Land>
        <Vertreter Geschlecht ="Männlich"> Giorgos Alkeos/Friends </Vertreter>
        <Song Sprache ="gr"> OPA! </Song>
        <grobePlatzierung>Finale</grobePlatzierung>
        <genauePlatzierung> 08 </genauePlatzierung>
    </Teilnehmer>
    
    <Teilnehmer> 
        <Land> Großbritannien </Land>
        <Vertreter Geschlecht ="Männlich"> Josh </Vertreter>
        <Song Sprache ="en"> That Sounds Good to Me </Song>
        <grobePlatzierung>Finale</grobePlatzierung>
        <genauePlatzierung> 25 </genauePlatzierung>
    </Teilnehmer>
    
    <Teilnehmer> 
        <Land> Irland </Land>
        <Vertreter Geschlecht ="Weiblich"> Niamh Kavanagh </Vertreter>
        <Song Sprache ="en"> It’s for You </Song>
        <grobePlatzierung>Finale</grobePlatzierung>
        <genauePlatzierung> 23 </genauePlatzierung>
    </Teilnehmer>
    
    <Teilnehmer> 
        <Land> Island </Land>
        <Vertreter Geschlecht ="Weiblich"> Hera Björk </Vertreter>
        <Song Sprache ="en"> Je ne sais quoi </Song>
        <grobePlatzierung>Finale</grobePlatzierung>
        <genauePlatzierung> 19 </genauePlatzierung>
    </Teilnehmer>
    
    <Teilnehmer> 
        <Land> Israel </Land>
        <Vertreter Geschlecht ="Männlich"> Harel Skaat </Vertreter>
        <Song Sprache ="heb"> Milim </Song>
        <grobePlatzierung>Finale</grobePlatzierung>
        <genauePlatzierung> 14 </genauePlatzierung>
    </Teilnehmer>
    
    <Teilnehmer> 
        <Land> Kroatien </Land>
        <Vertreter Geschlecht ="Weiblich"> Feminnem </Vertreter>
        <Song Sprache ="kr"> Lako je sve </Song>
        <grobePlatzierung>Halbfinale</grobePlatzierung>
        <genauePlatzierung> 13 </genauePlatzierung>
    </Teilnehmer>
    
    <Teilnehmer> 
        <Land> Lettland </Land>
        <Vertreter Geschlecht ="Weiblich"> Aisha </Vertreter>
        <Song Sprache ="en"> What For? </Song>
        <grobePlatzierung>Halbfinale</grobePlatzierung>
        <genauePlatzierung> 17 </genauePlatzierung>
    </Teilnehmer>
    
    <Teilnehmer> 
        <Land> Litauen </Land>
        <Vertreter Geschlecht ="Männlich"> InCulto </Vertreter>
        <Song Sprache ="en"> East European Funk </Song>
        <grobePlatzierung>Halbfinale</grobePlatzierung>
        <genauePlatzierung> 12 </genauePlatzierung>
    </Teilnehmer>
    
    <Teilnehmer> 
        <Land> Malta </Land>
        <Vertreter Geschlecht ="Weiblich"> Thea Garrett </Vertreter>
        <Song Sprache ="en"> My Dream </Song>
        <grobePlatzierung>Halbfinale</grobePlatzierung>
        <genauePlatzierung> 12 </genauePlatzierung>
    </Teilnehmer>
    
    <Teilnehmer> 
        <Land> Mazedonien </Land>
        <Vertreter Geschlecht ="Weiblich"> Gjoko Taneski </Vertreter>
        <Song Sprache ="maz"> Jas ja imam silata </Song>
        <grobePlatzierung>Halbfinale</grobePlatzierung>
        <genauePlatzierung> 15 </genauePlatzierung>
    </Teilnehmer>
    
    <Teilnehmer> 
        <Land> Moldau </Land>
        <Vertreter Geschlecht ="Gemischt"> SunStroke Project/Olia Tira </Vertreter>
        <Song Sprache ="en"> Run Away </Song>
        <grobePlatzierung>Finale</grobePlatzierung>
        <genauePlatzierung> 22 </genauePlatzierung>
    </Teilnehmer>
    
    <Teilnehmer> 
        <Land> Niederlande </Land>
        <Vertreter Geschlecht ="Weiblich"> Sieneke </Vertreter>
        <Song Sprache ="nl"> Ik ben verliefd </Song>
        <grobePlatzierung>Halbfinale</grobePlatzierung>
        <genauePlatzierung> 14 </genauePlatzierung>
    </Teilnehmer>
    
    <Teilnehmer> 
        <Land> Norwegen </Land>
        <Vertreter Geschlecht ="Männlich"> My Heart Is Yours </Vertreter>
        <Song Sprache ="en"> Didrik Solli-Tangen </Song>
        <grobePlatzierung>Finale</grobePlatzierung>
        <genauePlatzierung> 20 </genauePlatzierung>
    </Teilnehmer>
    
    <Teilnehmer> 
        <Land> Polen </Land>
        <Vertreter Geschlecht ="Männlich"> Marcin Mrozinski </Vertreter>
        <Song Sprache ="pol"> Legenda </Song>
        <grobePlatzierung>Halbfinale</grobePlatzierung>
        <genauePlatzierung> 13 </genauePlatzierung>
    </Teilnehmer>
    
    <Teilnehmer> 
        <Land> Portugal </Land>
        <Vertreter Geschlecht ="Weiblich"> Filipa Azevedo </Vertreter>
        <Song Sprache ="pt"> Ha dias assim </Song>
        <grobePlatzierung>Finale</grobePlatzierung>
        <genauePlatzierung> 18 </genauePlatzierung>
    </Teilnehmer>
    
    <Teilnehmer> 
        <Land> Rumänien </Land>
        <Vertreter Geschlecht ="Weiblich"> Paula Seling/Ovi </Vertreter>
        <Song Sprache ="en"> Playing with Fire </Song>
        <grobePlatzierung>Finale</grobePlatzierung>
        <genauePlatzierung> 03 </genauePlatzierung>
    </Teilnehmer>
